<a href="https://colab.research.google.com/github/JM-Ferreras/58013-Linear-Algebra/blob/main/Experiment_Num9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import numpy as np

A = np.array([[2, 4, 6],
              [8, 10, -2],
              [-4, -6, -8]])

B = np.array([[-7, -5, -3],
              [-1, 9, 7],
              [5, 3, 1]])

C = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

I = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])

O = np.array([[0, 0, 0],
              [0, 0, 0],
              [0, 0, 0]])

Y = np.array([[1, 2],
              [3, 4],
              [5, 6]])

Z = np.array([[7, 8, 9, 10],
              [11, 12, 13, 14]])

print("Matrices:")

print("A:","\n",A)
print("B:","\n",B)
print("C:","\n",C)
print("I:","\n",I)
print("O:","\n",O)

print("\n"+"Not a commutative property:")
print("A × B:")
print(np.dot(A,B))
print("B × A:")
print(np.dot(B,A))

print("\n"+"Associative property:")
print("A × (B × C):")
AB=np.dot(A,B)
ABC=np.dot(AB,C)
print(ABC)
print("(A × B) × C:")
BC=np.dot(B,C)
ABC2=np.dot(A,BC)
print(ABC2)

print("\n"+"Distributive property:")
print("A × (B + C):")
BpC=np.add(B,C)
print(np.dot(A,BpC))
print("(A × B) + (A × C):")
print(np.add(np.dot(A,B),np.dot(A,C)))

print("\n"+"Multiplicative Identity Property:")
print("I × A = A")
print(np.dot(I,A))
print("A × I = A")
print(np.dot(A,I))

print("\n"+"Multiplicative Property of Zero:")
print("O × A = O:")
print(np.dot(O,A))
print("A × O = O:")
print(np.dot(A,O))

print("\n"+"Dimension Property:")
print("(4 × 2) ⋅ (2 × 4) = 4 × 4")
result = np.dot(Y, Z)
dim_Y = Y.shape
dim_Z = Z.shape
dim_result = result.shape

print("Matrix Y ({}x{}):".format(dim_Y[0], dim_Y[1]))
print(Y)
print("Matrix Z ({}x{}):".format(dim_Z[0], dim_Z[1]))
print(Z)
print("Result ({}x{}):".format(dim_result[0], dim_result[1]))
print(result)


Matrices:
A: 
 [[ 2  4  6]
 [ 8 10 -2]
 [-4 -6 -8]]
B: 
 [[-7 -5 -3]
 [-1  9  7]
 [ 5  3  1]]
C: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
I: 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
O: 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

Not a commutative property:
A × B:
[[ 12  44  28]
 [-76  44  44]
 [ -6 -58 -38]]
B × A:
[[-42 -60  -8]
 [ 42  44 -80]
 [ 30  44  16]]

Associative property:
A × (B × C):
[[ 384  468  552]
 [ 408  420  432]
 [-504 -606 -708]]
(A × B) × C:
[[ 384  468  552]
 [ 408  420  432]
 [-504 -606 -708]]

Distributive property:
A × (B + C):
[[  72  116  112]
 [ -42   94  110]
 [ -90 -160 -158]]
(A × B) + (A × C):
[[  72  116  112]
 [ -42   94  110]
 [ -90 -160 -158]]

Multiplicative Identity Property:
I × A = A
[[ 2  4  6]
 [ 8 10 -2]
 [-4 -6 -8]]
A × I = A
[[ 2  4  6]
 [ 8 10 -2]
 [-4 -6 -8]]

Multiplicative Property of Zero:
O × A = O:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
A × O = O:
[[0 0 0]
 [0 0 0]
 [0 0 0]]

Dimension Property:
(4 × 2) ⋅ (2 × 4) = 4 × 4
Matrix Y (3x2):
[[1 2]
 [3 4]
 [5 6]]
Matrix Z (2x4):
[[ 7 