<a href="https://colab.research.google.com/github/JM-Ferreras/58013-Linear-Algebra/blob/main/Lab%20No5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

A = np.array([1,5,8,9])
S = 5*A
S

S = np.multiply(5,A)
S


array([ 5, 25, 40, 45])

In [9]:
A = np.array([1,5,8,9])
S = 5*A
print(S)

[ 5 25 40 45]


In [8]:
S = np.multiply(5,A)
print(S)


[ 5 25 40 45]


In [4]:
import numpy as np
p = [4, 2]
q = [5, 6]
product = np.cross(p,q)
print(product)


14
