<a href="https://colab.research.google.com/github/JM-Ferreras/58013-Linear-Algebra/blob/main/Long%20Quiz%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import numpy as numpy

#Prob 1
A=numpy.array([[1,2,3],
             [4,5,6]])

B=numpy.array([[1,2],
              [3,4],
              [5,6]])

print('A. AB (as numpy.dot(A,B))')
print(numpy.dot(A,B))
print('\n')

D=numpy.array([[1,2],
               [3,4]])

print('B. D+D (as D*2)')
print(D*2)
print('B. Alternative) D+D as numpy.add(D,D)')
print(numpy.add(D,D))
print('\n')

C=numpy.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

print('C. 2C (as C*2)')
print(C*2)
print('C. Alternative) numpy.add(C,C)')
print(numpy.add(C,C))

A. AB (as numpy.dot(A,B))
[[22 28]
 [49 64]]


B. D+D (as D*2)
[[2 4]
 [6 8]]
B. Alternative) D+D as numpy.add(D,D)
[[2 4]
 [6 8]]


C. 2C (as C*2)
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
C. Alternative) numpy.add(C,C)
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [31]:
import numpy as numpy

#Prob2

A=numpy.array([2,7,4])
B=numpy.array([3,9,8])
print("Cross product of A and B:")
print(numpy.cross(A,B))

Cross product of A and B:
[20 -4 -3]
