<a href="https://colab.research.google.com/github/JM-Ferreras/58013-Linear-Algebra/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#Question 1) Create a Multiplication Table/Chart of 1 to 10 using numpy/ python program.

import numpy as np

row1= np.array([1,2,3,4,5,6,7,8,9,10])
i=1
while i<=10:
  print(row1*i)
  i+=1


[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10 12 14 16 18 20]
[ 3  6  9 12 15 18 21 24 27 30]
[ 4  8 12 16 20 24 28 32 36 40]
[ 5 10 15 20 25 30 35 40 45 50]
[ 6 12 18 24 30 36 42 48 54 60]
[ 7 14 21 28 35 42 49 56 63 70]
[ 8 16 24 32 40 48 56 64 72 80]
[ 9 18 27 36 45 54 63 72 81 90]
[ 10  20  30  40  50  60  70  80  90 100]


In [2]:
#Question 2. (10 points) In relation to Question 1, show a solution that doubles all the values of each element.

import numpy as np

row1= np.array([1,2,3,4,5,6,7,8,9,10])
i=1
print(row1)
while i<=10:
  row1=row1*2
  print(row1)
  i+=1

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10 12 14 16 18 20]
[ 4  8 12 16 20 24 28 32 36 40]
[ 8 16 24 32 40 48 56 64 72 80]
[ 16  32  48  64  80  96 112 128 144 160]
[ 32  64  96 128 160 192 224 256 288 320]
[ 64 128 192 256 320 384 448 512 576 640]
[ 128  256  384  512  640  768  896 1024 1152 1280]
[ 256  512  768 1024 1280 1536 1792 2048 2304 2560]
[ 512 1024 1536 2048 2560 3072 3584 4096 4608 5120]
[ 1024  2048  3072  4096  5120  6144  7168  8192  9216 10240]


In [3]:
#Question 3. (10 points) Create a square matrix that has a diagonal 1's.

import numpy as np

row1=np.array([[1,0,0,0,0],
               [0,1,0,0,0],
               [0,0,1,0,0],
               [0,0,0,1,0],
               [0,0,0,0,1]])
print(row1)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [11]:
#Question 4. (30 points) Create a matrix whose elements are:

import numpy as np

row1 = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

print('Matrix size:',row1.size)
print('Matrix shape:',row1.shape)
print('Matrix Dimensions:',row1.ndim)

Matrix size: 12
Matrix shape: (3, 4)
Matrix Dimensions: 2


In [9]:
#Question 5. (30 points) Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element.
import numpy as np
arr1=np.array([[5,6,9],[21,18,27]])
arr2=np.array([[15,33,24],[4,7,1]])
sum=np.add(arr1,arr2)
print('Sum:\n',sum,'\n')
sqr=sum**2
print('Square of Sum:\n',sqr)

Sum:
 [[20 39 33]
 [25 25 28]] 

Square of Sum:
 [[ 400 1521 1089]
 [ 625  625  784]]
