<a href="https://colab.research.google.com/github/JM-Ferreras/58013-Linear-Algebra/blob/main/Python_Exercise_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np
A = np.array([[-0.4],[4.3],[-0.6]])
B = np.array([-0.2,0.2,1])
C = np.array([-0.2,2.1,-1.5])

In [16]:
#Add
s=A+B+C
print(s)

[[-0.8  1.9 -0.9]
 [ 3.9  6.6  3.8]
 [-1.   1.7 -1.1]]


In [17]:
#Subtract
d=A-B-C
print(d)


[[ 0.  -2.7  0.1]
 [ 4.7  2.   4.8]
 [-0.2 -2.9 -0.1]]


In [18]:
#Multiply
p=A*B*C
print(p)

[[-0.016 -0.168  0.6  ]
 [ 0.172  1.806 -6.45 ]
 [-0.024 -0.252  0.9  ]]


In [19]:
#Divide
q=A/B/C
print(q)

[[-10.          -0.95238095   0.26666667]
 [107.5         10.23809524  -2.86666667]
 [-15.          -1.42857143   0.4       ]]
